Implement SendMail
EasyMicroservices/Emails-Microservice pull request #3
Opened 2023-08-22 13:27 UTC by Elyas-Amini

## Description

### Related issue(s)

### Checklist:

- [ ] It refers to an [Issue](https://github.com/EasyMicroservices/FileManager/issues).
- [ ] It fixes a bug.
- [x] It's a new feature (non-breaking change which adds functionality)
- [ ] It's a breaking (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] CHANGELOG is updated.
- [ ] Related language label is selected.

2023-08-22 13:30 UTC, MahdiyarGHD approved these changes

2023-08-22 13:32 UTC, Ali-YousefiTelori requested changes

2023-08-22 13:32 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.EmailsMicroservice.Domain/Contracts/Common/SendMailContract.cs
> +    public class SendMailContract
renames it to SendEmailContract

2023-08-22 13:32 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.EmailsMicroservice.WebApi/EasyMicroservices.EmailsMicroservice.WebApi.csproj
> +    <PackageReference Include="Abp" Version="8.3.1" />
```suggestion
```

2023-08-22 13:32 UTC, Hamed-Bagherpour approved these changes

2023-08-24 10:31 UTC, Ali-YousefiTelori approved these changes

2023-08-24 10:31 UTC, merged